spring:
  cloud:
    config:
      label: master
      url: http://localhost:8888/config_repos

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#  zipkin:
#    base-url: http://localhost:10085
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#  boot:
#    admin:
#      client:
#        url: http://localhost:8084
