server:
  port: 9010
spring:
  application:
    name: weixin-pay
weixin:
  appid: wx8397f8696b538317 #微信公众账号或开放平台APP的唯一标识
  mch_id: 1473426802 #商户号 
  key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb #商户密钥
  partner: 1473426802
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  notifyurl: http://www.itcast.cn
