spring:
  rabbitmq:                    #本地环境不需要配置mq，但是需要启动mq,Springboot会自动连接本地mq
    host: 116.196.77.250
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        -id: query_route
        uri: config-server
        predicates:
          -Query=foo, ba.