server:
  port: 8083
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
fdfs:
  web-server-url: 116.196.77.250:8080
  connect-timeout: 601
  http:
    anti_steal_token: true
    secret_key: FastDFS1234567890
    so-timeout: 1501
    thumb-image:
      height: 150
      width: 150
  nginx-host: 116.196.77.250:8080
  tracker-list:
    - 116.196.77.250:22122